[package]
name = "sleipnirdb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3.0"